name: CI to Docker Hub

# 액션 실행 트리거 속성 설정
# Github 저장소의 main 브랜치에 코드가 push(업데이트)될 때 작동
on:
  push:
    branches:
      - main
    # HW2 폴더에 변경사항이 있을 때만 빌드 동작 (효율성 극대화)
    paths:
      - 'HW2/**'

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest # 깃허브가 제공하는 우분투 환경 컨테이너 위에서 실행
    
    steps:
      # 1. 깃허브 저장소의 내 코드 불러오기
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      # 2. 고급 도커 빌드 툴(Buildx) 세팅: 레이어 캐싱 및 다중 아키텍처 빌드 기능 제공
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Docker Hub 로그인 (보안 정보는 Github Secrets을 이용해 주입)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. 도커 이미지 빌드 및 푸시 (GitHub Actions 도커 캐시 기능 활용으로 빌드 시간 대폭 단축)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./HW2 # Dockerfile이 위치한 경로를 지정
          file: ./HW2/Dockerfile
          push: true
          # 레지스트리에 저장될 태그 이름
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mushroom-api:latest
          # 도커 레이어 캐싱 설정: 이후 동일한 파일 재빌드 시 속도가 매우 빨라집니다.
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mushroom-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mushroom-api:buildcache,mode=max
